[tool.poetry]
name = "gpg_keymanager"
version = "1.0"
description = "gpg pass password store keyring management"
authors = ["Ilkka Tuohela <hile@iki.fi>"]
license = "PSF"

[tool.poetry.dependencies]
python = "^3.9"
pathlib-tree = "^2.1.6"

[tool.poetry.dev-dependencies]
coverage = "^6.1"
flake8 = "^4.0"
flake8-bugbear = "^21.9"
flake8-quotes = "^3.3"
pycodestyle = "^2.8"
pyflakes = "^2.4"
pylint = "^2.11"
pytest = "^6.2"
tox = "^3"

[build-system]
requires = ["poetry-core>=1.0.8"]
build-backend = "poetry.core.masonry.api"
